-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Nov 25, 2025 at 03:20 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `savvy3`
--

-- --------------------------------------------------------

--
-- Table structure for table `agent_payment_gateway`
--

CREATE TABLE `agent_payment_gateway` (
  `id` int(11) NOT NULL,
  `un_id` varchar(255) NOT NULL,
  `agent_un_id` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `receiver_address` varchar(255) NOT NULL,
  `diposit_working` int(11) NOT NULL,
  `withdraw_working` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `description` text NOT NULL,
  `input_form` text NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `app_key` varchar(255) NOT NULL,
  `app_secret_key` varchar(255) NOT NULL,
  `call_back_url` text NOT NULL,
  `type` enum('api','manual','cashOut','bank') NOT NULL,
  `created_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `agent_payment_gateway`
--

INSERT INTO `agent_payment_gateway` (`id`, `un_id`, `agent_un_id`, `image`, `name`, `receiver_address`, `diposit_working`, `withdraw_working`, `status`, `description`, `input_form`, `username`, `password`, `app_key`, `app_secret_key`, `call_back_url`, `type`, `created_at`) VALUES
(1, 'asydada', 'djfsgdjb', 'https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/06/dc/9b06dcfa-16f6-9ca1-0daf-c9cc27d03337/APPICON_PRODUCTION-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x1024bb.png', 'Bkash', '123456', 0, 0, 0, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01720550121', 'U6-4hNYNVc%', 'goenQBcyo6cBDG9DXtcDIp1Utc', '4DaDSKC0Wqr6zTy1vDh8MKdfcc2PAgYppN0Fb8r3ZB9vfKoFGF6J', 'https://mysavvybd.com/', 'api', '2024-08-14 14:46:31'),
(2, 'asydada', 'djfsgdjb', 'https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/06/dc/9b06dcfa-16f6-9ca1-0daf-c9cc27d03337/APPICON_PRODUCTION-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x1024bb.png', 'Bkash', '123456', 1, 1, 1, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01615426234', 'E?MB1KAy:hq', 'SJ3snWeEUqnrPA8wVbn7oJ8ltc', 'EtJ4osGWIykt9JWoOom6TjctLA7sm3XOZOUW7FOFzVseyFbM4xWo', 'https://mysavvybd.com/', 'api', '2024-08-14 14:46:31'),
(3, 'asydadaasd', 'ahsdvdjcv', 'https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/06/dc/9b06dcfa-16f6-9ca1-0daf-c9cc27d03337/APPICON_PRODUCTION-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x1024bb.png', 'Bkash', '01615426234', 1, 1, 0, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01615426234', 'E?MB1KAy:hq', 'SJ3snWeEUqnrPA8wVbn7oJ8ltc', 'EtJ4osGWIykt9JWoOom6TjctLA7sm3XOZOUW7FOFzVseyFbM4xWo', 'https://mysavvybd.com/', 'api', '2024-08-14 14:46:31'),
(4, 'wueyfbf', 'ahsdvdjcv', 'https://freelogopng.com/images/all_img/1679248787Nagad-Logo.png', 'Nagad (Cashout)', '01810224190', 1, 1, 0, '', '', '', '', '', '', 'https://mysavvybd.com/', 'manual', '2024-12-12 13:14:01'),
(5, 'awfgdbf', 'ahsdvdjcv', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', '.... Please contact your agent to get account information.', 1, 1, 1, '', '', '', '', '', '', '', 'manual', '2024-12-12 13:19:07'),
(6, '67836b7af2195', 'ahsdvdjcv', 'https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/06/dc/9b06dcfa-16f6-9ca1-0daf-c9cc27d03337/APPICON_PRODUCTION-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x1024bb.png', 'Bkash', '01728048455', 1, 1, 0, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01728048455', 'h:vrz=G18HS', 'n75AJI5XpMmGRL7Wl6jbMzIvtc', 'cA6auPNxEUXhhysJ3j7PVcd1dDfpM79bIbWWr0rkRIpEtCPwFVTj', 'https://mysavvybd.com/', 'api', '2024-08-14 14:46:31'),
(7, 'wueyfbfasrwqe', 'ahsdvdjcv', 'https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/06/dc/9b06dcfa-16f6-9ca1-0daf-c9cc27d03337/APPICON_PRODUCTION-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x1024bb.png', 'Bkash (Cashout)', '01810224190', 1, 1, 0, '', '', '', '', '', '', 'https://mysavvybd.com/', 'manual', '2024-12-12 13:14:01'),
(8, 'asydadaasdasd', '681f1cfc08f53', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', '.... Please contact your agent to get account information.', 1, 1, 1, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01615426234', 'E?MB1KAy:hq', 'SJ3snWeEUqnrPA8wVbn7oJ8ltc', 'EtJ4osGWIykt9JWoOom6TjctLA7sm3XOZOUW7FOFzVseyFbM4xWo', 'https://mysavvybd.com/', 'manual', '2024-08-14 14:46:31'),
(9, '67836b7af2195we', '681f1cfc08f53', 'https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/06/dc/9b06dcfa-16f6-9ca1-0daf-c9cc27d03337/APPICON_PRODUCTION-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x1024bb.png', 'Bkash', '01911071707', 1, 1, 1, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01911071707', 'JAe+*rI]6eo', 'hqw4JgraIiPlVrjQYPzWtx34tc', '7VIjGRnF02IueTfMknc9iMwTlKLhWRcyBYghShh2mm2UqAVxW9Lu', 'https://mysavvybd.com/', 'api', '2025-06-02 14:46:31'),
(10, 'asydadaasdasdwed', '683ecdad20fa0', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', '.... Please contact your agent to get account information.', 1, 1, 1, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01615426234', 'E?MB1KAy:hq', 'SJ3snWeEUqnrPA8wVbn7oJ8ltc', 'EtJ4osGWIykt9JWoOom6TjctLA7sm3XOZOUW7FOFzVseyFbM4xWo', 'https://mysavvybd.com/', 'manual', '2025-06-03 14:46:31'),
(11, '683ecdad20fa0bvb', '683ecdad20fa0', 'https://is4-ssl.mzstatic.com/image/thumb/Purple114/v4/9b/06/dc/9b06dcfa-16f6-9ca1-0daf-c9cc27d03337/APPICON_PRODUCTION-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/1024x1024bb.png', 'Bkash', '683ecdad20fa0', 1, 1, 1, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01717913954', '6hnjI9cn*3i', 'PT8sfLI7j2XaMZ0qij5OJAG8tc', 'KK8r3qKcD4tgfaG4xwK1D0RBG8IUTZvqtce7XPg5C0QIfghgwcBO', 'https://mysavvybd.com/', 'api', '2024-08-14 14:46:31'),
(12, 'safuwefwf34f3', '685816d83c7fa', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', '.... Please contact your agent to get account information.', 1, 1, 1, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '01615426234', 'E?MB1KAy:hq', 'SJ3snWeEUqnrPA8wVbn7oJ8ltc', 'EtJ4osGWIykt9JWoOom6TjctLA7sm3XOZOUW7FOFzVseyFbM4xWo', 'https://mysavvybd.com/', 'manual', '2025-06-22 20:54:31'),
(13, 'safuwefwf34f3sdf', '6885bab18fae5', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', 'Bank Name: Dutch Bangla Bank \nName:Tanay Ray \nBranch: Shewrapara \nBank Account number : 3081580204758\nRouting Number - 090264272', 1, 1, 1, 'Our Agent Bkash number:&nbsp;01310774995 (<b>BD Agent</b>)<div>Cashout to this number.</div><div><br></div><div><font color=\"#ff3399\">Note:&nbsp;</font><span style=\"font-size: 1rem;\"><font color=\"#0066ff\">Maximum transaction limit once in a day from one number</font></span></div><div><br></div><div><font color=\"#ff0000\" size=\"2\">Make sure you are submitting correct details. If you make submit any wrong details you may lose your money.. So double check your sender number/trxid/screenshot before clicking pay now.</font></div>', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '', '', '', '', 'https://mysavvybd.com/', 'manual', '2025-07-28 20:54:31'),
(14, 'safuweiufwf34f3', '6899a9b4bf765', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', 'Bank Name: Dutch Bangla Bank \r\nName:MD. MOSFEKUR RAHMAN\r\nBranch: Mirpur10 \r\nBank Account number : 1641580050261\r\nRouting Number - 090263136', 1, 1, 1, '', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '', '', '', '', 'https://mysavvybd.com/', 'manual', '2025-07-28 20:54:31'),
(15, '689a1789be6ca', '689a171d79af4', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', 'Bank Name: Dutch Bangla Bank \r\nName:MD.Akhtarul  Islam\r\nBranch: Elephant Road\r\nBank Account number : 1261010295460\r\nRouting Number - 090261338\r\nPhone Number: 01712533191', 1, 1, 1, '', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '', '', '', '', 'https://mysavvybd.com/', 'manual', '2025-07-28 20:54:31'),
(16, '689a1789be6ca54', '68a1e8e59696e', 'https://cdn-icons-png.flaticon.com/128/3771/3771527.png', 'Bank Transfer', 'Bank Name: Dutch Bangla Bank \r\nName:Syed Imtiaz Hossain\r\nBranch: CDA Avenue, Chittagong\r\nBank Account number : 1331010009710\r\nRouting Number - 090150131\r\nPhone Number: 01819389448', 1, 1, 1, '', '{\"sender_bkash_number\":{\"field_name\":\"sender_bkash_number\",\"field_level\":\"Sender bkash number\",\"type\":\"text\",\"validation\":\"required\"},\"transaction_id\":{\"field_name\":\"transaction_id\",\"field_level\":\"Transaction ID\",\"type\":\"text\",\"validation\":\"required\"},\"cashout_screenshot\":{\"field_name\":\"cashout_screenshot\",\"field_level\":\"Cashout screenshot\",\"type\":\"file\",\"validation\":\"nullable\"}}', '', '', '', '', 'https://mysavvybd.com/', 'manual', '2025-08-18 18:24:31');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `agent_payment_gateway`
--
ALTER TABLE `agent_payment_gateway`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `agent_payment_gateway`
--
ALTER TABLE `agent_payment_gateway`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
