<?php include('header.php') ?>
<?php include('topbar.php') ?>
<?php include('flashdata.php') ?>

<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">

    <div class="card">
      <h5 class="card-header d-flex justify-content-between align-items-center">
        My Regular Programs Inventory
        <a href="<?= base_url('regularPrograms') ?>" class="btn btn-sm btn-primary">
          <i class="bx bx-plus"></i> Buy More Regular Programs
        </a>
      </h5>
      
      <div class="card-body">
        <?php if (isset($totalPrograms) && $totalPrograms > 0) { ?>
        <div class="mt-4">
          <div class="row">
            <div class="col-md-4">
              <div class="card bg-primary text-white">
                <div class="card-body">
                  <h5 class="text-white">Total Regular Programs</h5>
                  <h2 class="text-white"><?= $totalPrograms ?></h2>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card bg-success text-white">
                <div class="card-body">
                  <h5 class="text-white">Available</h5>
                  <h2 class="text-white"><?= $availablePrograms ?></h2>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card bg-info text-white">
                <div class="card-body">
                  <h5 class="text-white">Sold</h5>
                  <h2 class="text-white"><?= $soldPrograms ?></h2>
                </div>
              </div>
            </div>
          </div>
        </div>
        <?php } ?>
        
        <div class="table-responsive text-nowrap">
          <table class="table table-hover" id="programsTable">
            <thead>
              <tr>
                <th>ID</th>
                <th>Regular Program</th>
                <th>Price</th>
                <th>Status</th>
                <th>Customer</th>
                <th>Sold Date</th>
                <th>Purchase Date</th>
              </tr>
            </thead>
            <tbody id="programsTableBody">
              <?php if (empty($myPrograms)) { ?>
                <tr>
                  <td colspan="7" class="text-center">No regular programs in inventory</td>
                </tr>
              <?php } else { ?>
                <?php
                $n = 1;
                foreach ($myPrograms as $prog) { ?>
                  <tr class="program-row" data-index="<?= $n ?>">
                    <td><?= $n++ ?></td>
                    <td><?= htmlspecialchars($prog['title']) ?></td>
                    <td><?= number_format($prog['price'], 2) ?> ৳</td>
                    <td>
                      <?php if ($prog['status'] == 0) { ?>
                        <span class="badge bg-secondary">Pending</span>
                      <?php } elseif ($prog['status'] == 1) { ?>
                        <span class="badge bg-success">Available</span>
                      <?php } else { ?>
                        <span class="badge bg-info">Sold</span>
                      <?php } ?>
                    </td>
                    <td>
                      <?php if (!empty($prog['customer_un_id'])) { ?>
                        <?= $prog['customer_un_id'] ?>
                      <?php } else { ?>
                        <span class="text-muted">-</span>
                      <?php } ?>
                    </td>
                    <td>
                      <?php if (!empty($prog['sold_at'])) { ?>
                        <?= date('M d, Y', strtotime($prog['sold_at'])) ?>
                      <?php } else { ?>
                        <span class="text-muted">-</span>
                      <?php } ?>
                    </td>
                    <td><?= date('M d, Y', strtotime($prog['created_at'])) ?></td>
                  </tr>
                <?php } ?>
              <?php } ?>
            </tbody>
          </table>
        </div>

        <?php if (!empty($myPrograms) && count($myPrograms) > 20) { ?>
        <div class="d-flex justify-content-between align-items-center mt-4">
          <div class="text-muted" id="paginationInfo">
            Showing <span id="showingFrom">1</span> to <span id="showingTo">20</span> of <span id="totalEntries"><?= count($myPrograms) ?></span> entries
          </div>
          <nav aria-label="Page navigation">
            <ul class="pagination" id="paginationControls">
              <!-- Pagination will be generated by JavaScript -->
            </ul>
          </nav>
        </div>
        <?php } ?>
        
      </div>
    </div>

  </div>
</div>

<script>
// JavaScript Pagination
(function() {
    const rowsPerPage = 20;
    let currentPage = 1;
    const rows = document.querySelectorAll('.program-row');
    const totalRows = rows.length;
    const totalPages = Math.ceil(totalRows / rowsPerPage);

    if (totalRows <= rowsPerPage) {
        // No pagination needed
        return;
    }

    function displayPage(page) {
        const start = (page - 1) * rowsPerPage;
        const end = start + rowsPerPage;

        // Hide all rows
        rows.forEach((row, index) => {
            if (index >= start && index < end) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });

        // Update info text
        document.getElementById('showingFrom').textContent = start + 1;
        document.getElementById('showingTo').textContent = Math.min(end, totalRows);
        document.getElementById('totalEntries').textContent = totalRows;

        // Update pagination controls
        renderPagination(page);

        // Scroll to top of table
        document.getElementById('programsTable').scrollIntoView({ behavior: 'smooth', block: 'start' });
    }

    function renderPagination(page) {
        const paginationControls = document.getElementById('paginationControls');
        paginationControls.innerHTML = '';

        // First button
        const firstLi = document.createElement('li');
        firstLi.className = 'page-item' + (page === 1 ? ' disabled' : '');
        firstLi.innerHTML = `<a class="page-link" href="#" data-page="1">First</a>`;
        paginationControls.appendChild(firstLi);

        // Previous button
        const prevLi = document.createElement('li');
        prevLi.className = 'page-item' + (page === 1 ? ' disabled' : '');
        prevLi.innerHTML = `<a class="page-link" href="#" data-page="${page - 1}">&laquo;</a>`;
        paginationControls.appendChild(prevLi);

        // Page numbers (show max 5 pages at a time)
        let startPage = Math.max(1, page - 2);
        let endPage = Math.min(totalPages, page + 2);

        if (endPage - startPage < 4) {
            if (startPage === 1) {
                endPage = Math.min(totalPages, startPage + 4);
            } else if (endPage === totalPages) {
                startPage = Math.max(1, endPage - 4);
            }
        }

        for (let i = startPage; i <= endPage; i++) {
            const pageLi = document.createElement('li');
            pageLi.className = 'page-item' + (i === page ? ' active' : '');
            pageLi.innerHTML = `<a class="page-link" href="#" data-page="${i}">${i}</a>`;
            paginationControls.appendChild(pageLi);
        }

        // Next button
        const nextLi = document.createElement('li');
        nextLi.className = 'page-item' + (page === totalPages ? ' disabled' : '');
        nextLi.innerHTML = `<a class="page-link" href="#" data-page="${page + 1}">&raquo;</a>`;
        paginationControls.appendChild(nextLi);

        // Last button
        const lastLi = document.createElement('li');
        lastLi.className = 'page-item' + (page === totalPages ? ' disabled' : '');
        lastLi.innerHTML = `<a class="page-link" href="#" data-page="${totalPages}">Last</a>`;
        paginationControls.appendChild(lastLi);

        // Add click handlers
        paginationControls.querySelectorAll('a.page-link').forEach(link => {
            link.addEventListener('click', function(e) {
                e.preventDefault();
                const targetPage = parseInt(this.getAttribute('data-page'));
                if (targetPage >= 1 && targetPage <= totalPages && targetPage !== currentPage) {
                    currentPage = targetPage;
                    displayPage(currentPage);
                }
            });
        });
    }

    // Initialize
    displayPage(1);
})();
</script>

<?php include('footer.php') ?>
